kind: pipeline
name: oas_cliente_ci

steps:
# - name: check_readme
#   image: jjvargass/qa_develoment:latest
#   commands:
#   - python /app/check_readme.py
#   when:
#     branch:
#     - develop
#     - feature/*
#     - release/*
#     event:
#     - push

# - name: check_branch
#   image: jjvargass/qa_develoment:latest
#   commands:
#   - python /app/check_branch.py -H ${DRONE_GIT_HTTP_URL}
#   when:
#     branch:
#     - develop
#     - feature/*
#     - release/*
#     event:
#     - push

# - name: check_commits
#   image: jjvargass/qa_develoment:latest
#   failure: ignore
#   commands:
#   - python /app/check_commits.py
#   when:
#     branch:
#     - develop
#     - feature/*
#     - release/*
#     event:
#     - push

# - name: prueba_unitarias
#   image: node:12.22.7
#   commands:
#   - npm i
#   - npm run test
#   when:
#     branch:
#     - unitest
#
# - name:  pruebas_linter
#   image: node:12.22.7
#   commands:
#   - npm i
#   - npm run lint
#   when:
#     branch:
#     - unitest

- name: run_sonar_scanner
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: SONAR_HOST
    sonar_token:
      from_secret: SONAR_TOKEN
    ver: 1.0
    exclusions: "**/node_modules/**,**/*.spec.ts,documentation/**"
  when:
    branch:
    - develop
    - feature/*
    - release/*
    event:
    - push

- name: nodejs_release
  image: node:16.20.2
  commands:
  - node --version
  - npm i
  - npm run build:test
  when:
    branch:
    - release/*
    event:
    - push

- name: nodejs_master
  image: node:16.20.2
  commands:
  - node --version
  - npm i
  - npm run build:prod
  when:
    branch:
    - master
    event:
    - push

- name: publish_s3_release
  image: plugins/s3
  settings:
    bucket: cliente-pruebas-sisgplan
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    region: us-east-1
    source: dist/**/*
    target: /${DRONE_REPO_NAME}
    strip_prefix: dist/
  when:
    branch:
    - release/*
    event:
    - push

- name: publish_s3_master
  image: plugins/s3
  settings:
    bucket: cliente-pruebas-sisgplan
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    region: us-east-1
    source: dist/**/*
    target: /${DRONE_REPO_NAME}
    strip_prefix: dist/
  when:
    branch:
    - master
    event:
    - push
